name: Create Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest, macos-13]
        include:
          - os: ubuntu-latest
            platform: linux
            binary_name: type-schema-linux
          - os: ubuntu-24.04-arm
            platform: linux
            binary_name: type-schema-linux-arm64
          - os: windows-latest
            platform: windows
            binary_name: type-schema-windows.exe
          - os: macos-latest
            platform: macos
            binary_name: type-schema-macos-arm64
          - os: macos-13
            platform: macos
            binary_name: type-schema-macos

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Install Linux Build Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest

      - name: Build Native Binary
        run: |
          clojure -T:build uber
          native-image --no-fallback -jar target/type-schema.jar -o type-schema -H:Name=target/${{ matrix.binary_name }} -H:ReflectionConfigurationFiles=reflect-config.json --initialize-at-build-time --enable-url-protocols=https,http

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            target/${{ matrix.binary_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}